name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Cập nhật phiên bản mới nhất

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Cập nhật phiên bản mới nhất
      with:
        node-version: 20  # Thiết lập phiên bản Node.js là 20

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./src
        args: >
          -Dsonar.projectKey=my_project_key
          -Dsonar.organization=my_organization
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
